"""Add external_id to proposals

Revision ID: 0e753a03bb3d
Revises: 3c847a899433
Create Date: 2026-01-31 20:31:43.141273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e753a03bb3d'
down_revision = '3c847a899433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('external_id', sa.String(), nullable=True))
    op.alter_column('proposals', 'proposal_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_proposals_external_id'), 'proposals', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposals_external_id'), table_name='proposals')
    op.alter_column('proposals', 'proposal_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('proposals', 'external_id')
    # ### end Alembic commands ###
