"""Add is_public to projects

Revision ID: 29912f84cb01
Revises: 0cec930deffe
Create Date: 2026-01-31 20:20:15.216718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29912f84cb01'
down_revision = '0cec930deffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###
