"""Add multichain fields

Revision ID: 3c847a899433
Revises: dbeb6b3ff889
Create Date: 2026-01-31 20:29:39.155284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c847a899433'
down_revision = 'dbeb6b3ff889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('chain_type', sa.String(), nullable=False, server_default='polkadot'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'chain_type')
    # ### end Alembic commands ###
