"""Add analytics and forecast models

Revision ID: 3dc549d507ce
Revises: a1aed0cfdda1
Create Date: 2026-01-31 20:11:23.936622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc549d507ce'
down_revision = 'a1aed0cfdda1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_metrics_date'), 'analytics_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_id'), 'analytics_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_project_id'), 'analytics_metrics', ['project_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_project_id'), 'forecasts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_project_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_analytics_metrics_project_id'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_id'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_date'), table_name='analytics_metrics')
    op.drop_table('analytics_metrics')
    # ### end Alembic commands ###
