"""Add projects table and relations

Revision ID: 4495c46549b9
Revises: 3c92432ac0b4
Create Date: 2026-01-31 20:02:13.868858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4495c46549b9'
down_revision = '3c92432ac0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('rpc_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('user_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.add_column('alert_rules', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alert_rules', 'projects', ['project_id'], ['id'])
    op.add_column('notification_channels', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification_channels', 'projects', ['project_id'], ['id'])
    op.add_column('proposals', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposals', 'projects', ['project_id'], ['id'])
    op.add_column('reports', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'projects', ['project_id'], ['id'])
    op.add_column('treasury_spends', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'treasury_spends', 'projects', ['project_id'], ['id'])
    op.add_column('votes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'votes', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'project_id')
    op.drop_constraint(None, 'treasury_spends', type_='foreignkey')
    op.drop_column('treasury_spends', 'project_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'project_id')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'project_id')
    op.drop_constraint(None, 'notification_channels', type_='foreignkey')
    op.drop_column('notification_channels', 'project_id')
    op.drop_constraint(None, 'alert_rules', type_='foreignkey')
    op.drop_column('alert_rules', 'project_id')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
