"""Add audit models

Revision ID: 674ce6f89558
Revises: 0e753a03bb3d
Create Date: 2026-01-31 20:35:12.567193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674ce6f89558'
down_revision = '0e753a03bb3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_auditor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_cases_id'), 'audit_cases', ['id'], unique=False)
    op.create_index(op.f('ix_audit_cases_project_id'), 'audit_cases', ['project_id'], unique=False)
    op.create_table('audit_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['audit_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_comments_case_id'), 'audit_comments', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_comments_id'), 'audit_comments', ['id'], unique=False)
    op.create_table('audit_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['audit_cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_evidence_case_id'), 'audit_evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_evidence_id'), 'audit_evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_evidence_id'), table_name='audit_evidence')
    op.drop_index(op.f('ix_audit_evidence_case_id'), table_name='audit_evidence')
    op.drop_table('audit_evidence')
    op.drop_index(op.f('ix_audit_comments_id'), table_name='audit_comments')
    op.drop_index(op.f('ix_audit_comments_case_id'), table_name='audit_comments')
    op.drop_table('audit_comments')
    op.drop_index(op.f('ix_audit_cases_project_id'), table_name='audit_cases')
    op.drop_index(op.f('ix_audit_cases_id'), table_name='audit_cases')
    op.drop_table('audit_cases')
    # ### end Alembic commands ###
