"""Add scoring models

Revision ID: a1aed0cfdda1
Revises: ea60919d42b9
Create Date: 2026-01-31 20:08:05.133571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aed0cfdda1'
down_revision = 'ea60919d42b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('score_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('transparency_score', sa.Float(), nullable=False),
    sa.Column('participation_score', sa.Float(), nullable=False),
    sa.Column('treasury_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_scores_id'), 'governance_scores', ['id'], unique=False)
    op.create_table('score_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_score_configs_id'), 'score_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_configs_id'), table_name='score_configs')
    op.drop_table('score_configs')
    op.drop_index(op.f('ix_governance_scores_id'), table_name='governance_scores')
    op.drop_table('governance_scores')
    # ### end Alembic commands ###
