"""Add compliance models

Revision ID: dbeb6b3ff889
Revises: ef4f204be90b
Create Date: 2026-01-31 20:27:07.613909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbeb6b3ff889'
down_revision = 'ef4f204be90b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_policies_id'), 'compliance_policies', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_policies_project_id'), 'compliance_policies', ['project_id'], unique=False)
    op.create_table('contract_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_events_id'), 'contract_events', ['id'], unique=False)
    op.create_index(op.f('ix_contract_events_project_id'), 'contract_events', ['project_id'], unique=False)
    op.create_table('compliance_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['contract_events.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_violations_id'), 'compliance_violations', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_violations_project_id'), 'compliance_violations', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_violations_project_id'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_id'), table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index(op.f('ix_contract_events_project_id'), table_name='contract_events')
    op.drop_index(op.f('ix_contract_events_id'), table_name='contract_events')
    op.drop_table('contract_events')
    op.drop_index(op.f('ix_compliance_policies_project_id'), table_name='compliance_policies')
    op.drop_index(op.f('ix_compliance_policies_id'), table_name='compliance_policies')
    op.drop_table('compliance_policies')
    # ### end Alembic commands ###
