"""Add project_id to alert_history

Revision ID: ea60919d42b9
Revises: 4495c46549b9
Create Date: 2026-01-31 20:03:40.584166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea60919d42b9'
down_revision = '4495c46549b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alert_history', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert_history', type_='foreignkey')
    op.drop_column('alert_history', 'project_id')
    # ### end Alembic commands ###
